### PR TITLE
add support for some built-in string format specifiers: date-time, da…

### PR DESCRIPTION
**Pull request by mxmlnkn**
The repo might profit from an uncrustify.cfg for better collaboration. For example, my editor is configured to not be able to insert tabs, which you seem to use among other code style decisions.

### CODE REVIEW

**Comment by pboettch** [comment]
There is a clang-format-file which allows indent and alignment fixes using clang-format.

**Comment by natfarleydev** [comment]
Is there a reason this is not merged in yet? This would be a very useful feature for me if it can be merged.

**Comment by pboettch** [comment]
integrated with some changes regarding how to use it, see README-file.

**Comment by natfarleydev** [comment]
The README mentions the default string format, but doesn't mention what `loader` is, is there any documentation on the arguments for the `json_validator` constructor? (the only examples in the README use the implicit constructor).

**Comment by pboettch** [comment]
The examples in the repo are showing how to use to loader-callback. Would be really nice if you could read and understand and make an attempt to contribute to the README.

It's often better someone from the "outside" explains it that the ones from the inside you think everything is soo easy.

**Pull request closed without merging**
