### PR TITLE
Vs2019fix

### PR DESCRIPTION
**Pull request by NissimHadar**
I don't really understand why this is an error...

### CODE REVIEW

**Comment by pboettch** [comment]
What was the error message? Maybe it is a C++ standard revision problem?!

**Comment by NissimHadar** [comment]
It is strange.   The code seems fine to me, but gives a compilation error
(parameter mismatch).  When I separated it into two function calls, it
compiles fine.
This is with Visual Studio 2019 Professional.

**Comment by pboettch** [comment]
Could you please post the exact error message as soon by your compiler and ideally the compile command line?

**Comment by NissimHadar** [comment]
This is what I did:

git clone https://github.com/pboettch/json-schema-validator.git
cd json-schema-validator
mkdir build && cd build
cmake ..

(cmake version 3.15.1)

Built through IDE (Visual Studio 2019 version 16.5.4)

What???  This time it compiled fine!!!

I have NO explanation!

**Comment by pboettch** [comment]
Hmm, when you clarified your situation and this PR is not needed anymore, do not hesitate to close it.

**Pull request closed without merging**
