### PR TITLE
Use explicit type conversion from json

### PR DESCRIPTION
**Pull request by qvfh83**
As detailed in https://github.com/nlohmann/json#implicit-conversions, it's recommended not to use implicit conversions from json. This change allows those using "JSON_ImplicitConversions" OFF in the nlohmann::json package to build this package without errors.

### CODE REVIEW

**Comment by pboettch** [comment]
I haven't got around making github actions yet for this project. Do all the unit-tests are still working?

**Comment by qvfh83** [comment]
Yes, I ran them locally and they're all still working - if you really want I can try to run them within a containerized environment but may take a me a while to find time.

**Comment by pboettch** [comment]
Great. Don't work on a local solution. If you have time it would be better to integrate github-actions to this project. There was once support for travis and we should do the same thing (compiling and running the unit-tests).

**Comment by qvfh83** [comment]
@pboettch added actions - didn't quite use the travis template but I think it's ok (just squashed to single commit).

**Comment by pboettch** [comment]
Thanks. Good idea to borrow from nlohmann! I think it'll need some changes however.

Could you make a dedicated PR addressing explicitly #174 ? Then I can integrate this one more easily.

**Pull request merged**
