### PR TITLE
First implementation of sub-schema-validation on request.

### PR DESCRIPTION
**Pull request by pboettch**
Addresses #149 and #135

### CODE REVIEW

**Comment by pboettch** [comment]
@dvstans I'd love you to check this PR. It address, IMO, a part of your request.

**Comment by dvstans** [comment]
Hi, sorry I've been and still am extremely busy with other issues. I'll check it out if I can find the time soon.

**Comment by pboettch** [comment]
No worries, no hurries. I just wanted to make sure that you saw this one.

**Comment by qu1ck** [comment]
Friendly ping. Would be nice to see this merged.

**Pull request merged**
