### PR TITLE
First approach to clean out

### PR DESCRIPTION
**Pull request by Finkman**
Draft sandbox for simplifying the cmake

Fixes #162

### CODE REVIEW

**Comment by pboettch** [comment]
Looks good.

**Comment by pboettch** [comment]
There is a test-script which tests the different build-options. I will see whether I can adapt it. 

Also, the README file needs to be changed to reflekt these changes.

**Comment by Finkman** [comment]
I corrected the readme, but you need to invest a little cause I am not familiar with your build-option tests.

**Comment by pboettch** [comment]
Thanks, I'm quite busy atm. I hope I will find some time soon to have look at this project.

**Comment by pboettch** [comment]
Does your PR takes into account this issue https://github.com/pboettch/json-schema-validator/issues/163 - is it related?

**Comment by vrince** [comment]
What about merging this? It would make life easier for the `json-schema-validator` users I think.

**Review by pboettch — APPROVED** [review]

**Comment by pboettch** [comment]
I'm approving and integrating it, without having tested it myself. I must be crazy.

**Pull request merged**
