### PR TITLE
Use Ragel generated RFC-5321/RFC-6531 Mailbox address parser

### PR DESCRIPTION
**Pull request by gene-hightower**
Generated code copied from: <https://github.com/gene-hightower/smtp-address-parser>

fixes: #152

### CODE REVIEW

**Comment by pboettch** [comment]
Could you try to fix the errors the CI reported?

**Comment by gene-hightower** [comment]
> Could you try to fix the errors the CI reported?

Oh, right. I've used C++17 without even really thinking about it.

**Comment by gene-hightower** [comment]
So, I'm proposing to require C++17, as it's the default version of C++ for GCC and Clang now if you don't specify something else, it's been the standard for over five years, and it's almost fully supported by the major compilers.

**Comment by pboettch** [comment]
Sorry for the late response.

I want to stick to nlohmann::json's requirements and this is C++11. Is it possible for you to change your code to make it work with only C++11 - features?

**Comment by gene-hightower** [comment]
> Is it possible for you to change your code to make it work with only C++11 - features?

Sure.

**Review by pboettch — APPROVED** [review]

**Comment by pboettch** [comment]
I rebased your changes and integrated them in a squashed commit.

**Pull request closed without merging**
