### PR TITLE
Add uri format check

### PR DESCRIPTION
**Pull request by sebasfalcone**
This PR aims to close the following [issue](https://github.com/pboettch/json-schema-validator/issues/226)

## Change log
- Added URI format validation (RFC 3986)
- Added tests for URI format
- Removed URI from WILL_FAIL list tests

### CODE REVIEW

**Comment by pboettch** [comment]
LGTM; but please get rid of the white-space changes in the CMakeLists.txt of the test-suite.

**Comment by sebasfalcone** [comment]
@pboettch I've run the clang-format to the CMakeLists.txt file, let me know if it's okay. Thanks for the help and quick responses!

**Comment by pboettch** [comment]
No, don't run clang-format on the cmake-lists-file. It's only for C/C++ files.

Just revert all your changes of the CMakeLists.txt-file and only commit your actual change.

**Comment by sebasfalcone** [comment]
What a mess I've made. Sorry for the waterfall of notification :)

**Comment by sebasfalcone** [comment]
Hello @pboettch, how's that going? Is this PR on any road-map for the project?

**Comment by pboettch** [comment]
I'm overloaded, I need to find some time to take a closer look to the open PRs.

**Pull request merged**
